# tkh-phase-2-project - Financial Fraud Detection - Transform notebook

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
# Load dataset
df = pd.read_csv('../data/PS_20174392719_1491204439457_log.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6362620 entries, 0 to 6362619
Data columns (total 11 columns):
 #   Column          Dtype
---  ------          -----
 0   step            int64
 1   type            str
 2   amount          float64
 3   nameOrig        str
 4   oldbalanceOrg   float64
 5   newbalanceOrig  float64
 6   nameDest        str
 7   oldbalanceDest  float64
 8   newbalanceDest  float64
 9   isFraud         int64
 10  isFlaggedFraud  int64
dtypes: float64(5), int64(3), str(3)
memory usage: 534.0 MB

In [4]:
# Make column names more easily readable
df_columns_fixed = df.copy()
df_columns_fixed.columns = [
    'step',
    'type',
    'amount',
    'name_orig',
    'old_balance_orig',
    'new_balance_orig',
    'name_dest',
    'old_balance_dest',
    'new_balance_dest',
    'is_fraud',
    'is_flagged_fraud'
]
df_columns_fixed

,step,type,amount,name_orig,old_balance_orig,new_balance_orig,name_dest,old_balance_dest,new_balance_dest,is_fraud,is_flagged_fraud
0,1,PAYMENT,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0,0
1,1,PAYMENT,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0,0
2,1,TRANSFER,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1,0
3,1,CASH_OUT,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1,0
4,1,PAYMENT,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...
6362615,743,CASH_OUT,339682.13,C786484425,339682.13,0.00,C776919290,0.00,339682.13,1,0
6362616,743,TRANSFER,6311409.28,C1529008245,6311409.28,0.00,C1881841831,0.00,0.00,1,0
6362617,743,CASH_OUT,6311409.28,C1162922333,6311409.28,0.00,C1365125890,68488.84,6379898.11,1,0
6362618,743,TRANSFER,850002.52,C1685995037,850002.52,0.00,C2080388513,0.00,0.00,1,0
6362619,743,CASH_OUT,850002.52,C1280323807,850002.52,0.00,C873221189,6510099.11,7360101.63,1,0

In [5]:
# Dummy encode the `type` feature
df_dummies = df_columns_fixed.copy()
dummies = pd.get_dummies(df_dummies['type'], drop_first=True)
dummies_col = [c.lower() for c in dummies.columns.to_list()]
df_dummies[dummies_col] = dummies
df_dummies.drop('type', axis=1, inplace=True)
df_dummies

,step,amount,name_orig,old_balance_orig,new_balance_orig,name_dest,old_balance_dest,new_balance_dest,is_fraud,is_flagged_fraud,cash_out,debit,payment,transfer
0,1,9839.64,C1231006815,170136.00,160296.36,M1979787155,0.00,0.00,0,0,False,False,True,False
1,1,1864.28,C1666544295,21249.00,19384.72,M2044282225,0.00,0.00,0,0,False,False,True,False
2,1,181.00,C1305486145,181.00,0.00,C553264065,0.00,0.00,1,0,False,False,False,True
3,1,181.00,C840083671,181.00,0.00,C38997010,21182.00,0.00,1,0,True,False,False,False
4,1,11668.14,C2048537720,41554.00,29885.86,M1230701703,0.00,0.00,0,0,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6362615,743,339682.13,C786484425,339682.13,0.00,C776919290,0.00,339682.13,1,0,True,False,False,False
6362616,743,6311409.28,C1529008245,6311409.28,0.00,C1881841831,0.00,0.00,1,0,False,False,False,True
6362617,743,6311409.28,C1162922333,6311409.28,0.00,C1365125890,68488.84,6379898.11,1,0,True,False,False,False
6362618,743,850002.52,C1685995037,850002.52,0.00,C2080388513,0.00,0.00,1,0,False,False,False,True
6362619,743,850002.52,C1280323807,850002.52,0.00,C873221189,6510099.11,7360101.63,1,0,True,False,False,False

In [6]:
# Drop extaneous features from dataframe
df_drop_extran = df_dummies.copy()
df_drop_extran.drop(['step', 'is_flagged_fraud', 'old_balance_orig', 'old_balance_dest', 'name_orig', 'name_dest'], axis=1, inplace=True)
df_drop_extran.sort_index(axis=1)
df_drop_extran

,amount,new_balance_orig,new_balance_dest,is_fraud,cash_out,debit,payment,transfer
0,9839.64,160296.36,0.00,0,False,False,True,False
1,1864.28,19384.72,0.00,0,False,False,True,False
2,181.00,0.00,0.00,1,False,False,False,True
3,181.00,0.00,0.00,1,True,False,False,False
4,11668.14,29885.86,0.00,0,False,False,True,False
...,...,...,...,...,...,...,...,...
6362615,339682.13,0.00,339682.13,1,True,False,False,False
6362616,6311409.28,0.00,0.00,1,False,False,False,True
6362617,6311409.28,0.00,6379898.11,1,True,False,False,False
6362618,850002.52,0.00,0.00,1,False,False,False,True
6362619,850002.52,0.00,7360101.63,1,True,False,False,False

In [7]:
# Save dataframe to csv file
filename = 'transform_data.csv'
df_drop_extran.to_csv(f'../data/{filename}', index=False)